### ISSUE TITLE
CRLF line endings shouldn't be used in repository

### ISSUE THREAD

**Issue by olexander-movchan** [ProgramEngineeringKPI/Introduction-To-Programming#1]
Using **CRLF** line endings is inconvenient for people who do not use Windows.

Line endings should be configured according to [this article](https://help.github.com/articles/dealing-with-line-endings/).

**Comment by VihlayewAlex** [comment]
+1 - There are a lot of Unix-like OS users there

**Comment by vvasiuk** [comment]
This tbh

**Comment by L4fter** [comment]
While it should be a consideration if you're dealing with a code, this repository is created to be viewed on github-pages site. And of course if you don't like this that's up to you to configure your local repo however you want.

**Comment by olexander-movchan** [comment]
@L4fter, but there are some files that can be used to test solutions.

**Comment by L4fter** [comment]
ok, whatever
