### ISSUE TITLE
Fixed width integer types

### ISSUE THREAD

**Issue by olexander-movchan** [ProgramEngineeringKPI/Introduction-To-Programming#2]
It is mentioned in 3rd assignment that there are no fixed width types in C/C++.
> Зауважте, що в С/С++ немає типів даних int8, int16 тощо.

But there are such types since C99 and C++11. Look for a [reference](http://en.cppreference.com/w/cpp/types/integer).

**Comment by L4fter** [comment]
Okay, but there are no int8 and int16 stuff, only int8_t, int16_t. HA-HA.

**Comment by olexander-movchan** [comment]
So, you shouldn't recommend someone to use int, short or__int16 for this purpose.

**Comment by L4fter** [comment]
I'm not recommending, i'm merely pointing out that the types used are just replacement for int, short and so forth
